query office($id: String){
    office(id: $id){
        addressLine1
        addressLine2
        city
        country
        employees{
            email
            extension
            firstName
            id
            jobTitle
            lastName
        }
        id
        phone
        postalCode
        state
        territory
    }
}