query orders($limit: Int, $offset: Int, $status: String){
    orders(limit: $limit, offset: $offset, status: $status){
        comments
        customer{
            addressLine1
            addressLine2
            city
            country
            creditLimit
            customerName
            firstName
            id
            lastName
            phone
            postalCode
            state
        }
        details{
            order
            orderLineNumber
            priceEach
            quantityOrdered
        }
        id
        orderDate
        requiredDate
        shippedDate
        status
    }
}